### ISSUE TITLE
Restarting a game doesn't reset back to Wave 1

### ISSUE THREAD

**Issue by ZetDude** [xithiox/towerdefense#2]

**Comment by ghost** [comment]
Resetting the game causes the wave to increment, but only up to the number of preset waves + 1.

**Comment by ghost** [comment]
Confirmed to be related to the first branch of the `if` statement in `getWave()` on line 180 of `scripts/sketch.js`. Evaluating only the contents of the `else` branch seems to fix both the reset not working and the number of waves being capped.

**Comment by ghost** [comment]
It seems like the `nextWave()` function is somehow being repeatedly called, which causes the wave to increment several times.

**Comment by ghost** [comment]
This has now been fixed with the new random enemy waves! Hurray! 🎉
