### ISSUE TITLE
Intermittent lag

### ISSUE THREAD

**Issue by ghost** [xithiox/towerdefense#9]
There seems to be something causing lag spikes to occur every once in a while. It occurs even when no towers or enemies present. Frame rate drops from roughly 60 FPS to as low as 20 or 30 for a few seconds at a time.

**Comment by xithiox** [comment]
Does not seem to be related to the number of enemies that are spawned—appears to occur just as much with only a few enemies as it does with many.

**Comment by ghost** [comment]
Confirmed to be unrelated to enemies.

**Comment by ghost** [comment]
This doesn't seem to be a problem anymore
